#ifndef NETWORKMANAGER_GLOBAL_H
#define NETWORKMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKMANAGER_LIBRARY)
#  define NETWORKMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKMANAGER_GLOBAL_H
